server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: project-service
          uri: lb://PROJECT-SERVICE
          predicates:
            - Path=/projects/**

management:
  endpoints:
    web:
      exposure:
        include: gateway,health,info
