spring:
  cloud:
    gateway:
      routes:
        - id: project-service
          uri: lb://project-service
          predicates:
            - Path=/projects/**
          filters:
            - StripPrefix=1
        - id: task-service
          uri: lb://task-service
          predicates:
            - Path=/tasks/**
          filters:
            - StripPrefix=1
